# Generated by Django 4.2.4 on 2026-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('sync_code', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='GUID из 1С')),
                ('model_type', models.CharField(db_index=True, max_length=100, verbose_name='Тип объекта 1С')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Слепок данных (строка JSON)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления на шлюзе')),
            ],
            options={
                'verbose_name': 'Объект синхронизации',
                'verbose_name_plural': 'Объекты синхронизации',
                'indexes': [models.Index(fields=['model_type', 'is_deleted'], name='Inventory_s_model_t_c741ce_idx')],
            },
        ),
    ]
