# Generated by Django 4.2.4 on 2026-10-02 17:01

import Inventory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_code",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Сквозной код"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Inventory.models.good_image_upload_path,
                        verbose_name="Изображение товара",
                    ),
                ),
                (
                    "is_serial",
                    models.BooleanField(
                        default=False, verbose_name="Учет по серийным номерам"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "килограмм"),
                            ("pcs", "штука"),
                            ("m", "метр"),
                            ("l", "литр"),
                        ],
                        default="pcs",
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "code_v7",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Код 1С7"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_code",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Сквозной код"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "can_create",
                    models.BooleanField(
                        default=False, verbose_name="Может создавать номенклатуру"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="ToolBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("real", "real"),
                            ("transfer", "transfer"),
                            ("reception", "reception"),
                            ("write_off", "write_off"),
                        ],
                        max_length=10,
                        verbose_name="Тип хранилища",
                    ),
                ),
                ("quantity", models.FloatField(default=0.0, verbose_name="Количество")),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="Inventory.good",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="Inventory.storage",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток",
                "verbose_name_plural": "Остатки",
            },
        ),
        migrations.CreateModel(
            name="CreateOrWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                ("quantity", models.FloatField(default=0.0, verbose_name="Количество")),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="Inventory.good",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="Inventory.storage",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция создания/списания",
                "verbose_name_plural": "Операции создания/списания",
            },
        ),
    ]
