# Generated by Django 4.2.4 on 2026-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobileuser",
            options={
                "ordering": ["id"],
                "verbose_name": "Мобильный пользователь",
                "verbose_name_plural": "Мобильные пользователи",
            },
        ),
        migrations.AddField(
            model_name="mobileuser",
            name="sync_code",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Уникальный код синхронизации 1С",
            ),
        ),
        migrations.AlterField(
            model_name="mobileuser",
            name="can_create_nomenclature",
            field=models.BooleanField(
                default=False, verbose_name="Может создавать номенклатуру (поступления)"
            ),
        ),
    ]
