# Generated by Django 4.2.4 on 2026-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="category",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Категория"
            ),
        ),
    ]
