# Generated by Django 4.2.4 on 2026-10-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0002_alter_mobileuser_options_mobileuser_sync_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Полное имя"
            ),
        ),
    ]
