# Generated by Django 4.2.4 on 2026-10-10 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0003_mobileuser_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobileuser",
            name="full_name",
        ),
    ]
