# Generated by Django 4.2.4 on 2026-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0004_remove_mobileuser_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncAddressedItem",
            fields=[
                (
                    "storage_code",
                    models.CharField(
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        verbose_name="GUID склада-адерсата из 1С",
                    ),
                ),
                (
                    "sync_code",
                    models.CharField(
                        max_length=36, verbose_name="GUID объекта данных из 1С"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Тип объекта 1С"
                    ),
                ),
                (
                    "data",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Слепок данных (строка JSON)",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Флаг удаления"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления на шлюзе"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адресный объект синхронизации",
                "verbose_name_plural": "Адресные объекты синхронизации",
            },
        ),
        migrations.RemoveIndex(
            model_name="syncitem",
            name="Inventory_s_model_t_c741ce_idx",
        ),
        migrations.AddIndex(
            model_name="syncitem",
            index=models.Index(
                fields=["model_type", "sync_code"],
                name="Inventory_s_model_t_26b8f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncaddresseditem",
            index=models.Index(
                fields=["storage_code", "model_type", "sync_code"],
                name="Inventory_s_storage_3fe471_idx",
            ),
        ),
    ]
